name: 'Run gherkin-lint'
description: "A Github Action to parse and validate your feature files (gherkin / cucumber)"
author: 'nhatthm'
inputs:
  version:
    description: "Version of gherkin-lint to use in the `npm install -g gherkin-lint` command. Default to `latest`"
    required: false
    default: 'latest'
  feature_files:
    description: 'Comma separated list of feature files/glob patterns'
    required: false
    default: '.'
  config_file:
    description: 'Configuration file'
    required: false
    default: '/root/.gherkin-lintrc'
  format:
    description: 'Output format. Possible values: json, stylish, xunit. Default to `stylish`'
    required: false
    default: 'stylish'
  ignore:
    description: 'Comma seperated list of files/glob patterns that the linter should ignore, overrides .gherkin-lintignore file'
    required: false
    default: ''
  rule_dirs:
    description: 'Comma seperated list of additional rule directories'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "run-gherkin-lint"
branding:
  icon: "shield"
  color: "yellow"
